/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ztiany_ndksample_MainActivity */

#ifndef _Included_com_ztiany_ndksample_MainActivity
#define _Included_com_ztiany_ndksample_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ztiany_ndksample_MainActivity
 * Method:    callC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ztiany_ndksample_MainActivity_callC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
